<a href="https://colab.research.google.com/github/Abhinavpanjiyar1/100-days-python-projects/blob/main/Python_funadamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# EXERCISE OF PYTORCH FUNDAMENTALS

In [2]:
#Create a random tensor with shape (7, 7).

import torch
A= torch.rand(size=(7,7))
A, A.shape


(tensor([[0.2996, 0.1597, 0.1203, 0.6604, 0.0239, 0.5424, 0.6489],
         [0.2037, 0.4251, 0.5113, 0.6658, 0.2600, 0.8486, 0.4992],
         [0.6077, 0.7234, 0.1389, 0.0248, 0.9148, 0.8042, 0.7048],
         [0.1716, 0.7805, 0.7848, 0.9801, 0.6193, 0.9425, 0.9616],
         [0.9244, 0.9581, 0.4011, 0.6550, 0.8424, 0.6628, 0.1202],
         [0.5510, 0.4015, 0.4556, 0.1210, 0.6276, 0.1751, 0.9690],
         [0.4901, 0.4800, 0.6546, 0.5337, 0.8301, 0.5961, 0.9238]]),
 torch.Size([7, 7]))

In [4]:
#Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

B= torch.rand(size=(1,7))

C= torch.mm(A,B.T) # mm stands for matrix multiplication we can also use "MATMUL"
C, C.shape


(tensor([[0.6699],
         [1.1246],
         [1.2537],
         [1.5241],
         [1.4254],
         [0.8806],
         [1.3077]]),
 torch.Size([7, 1]))

In [1]:
#Set the random seed to 0 and do exercises 2 & 3 over again.

import torch
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

X= torch.rand(size= (7,7))
Y= torch.rand(size = (1,7))

Z= torch.mm(X, Y.T)
Z, Z.shape


(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [2]:
# Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

torch.cuda.manual_seed(1234)


In [3]:
#Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

torch.manual_seed(1234)
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
a= torch.rand(size=(2,3)).to(device)
b= torch.rand(size = (2,3)).to(device)
a , b


Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [5]:
# Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

c=torch.mm(a,b.T)
c,c.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

In [10]:
# Find the maximum and minimum values of the output of 7.
min = torch.min(c)
max = torch.max(c)
min, max

(tensor(0.3647, device='cuda:0'), tensor(0.5617, device='cuda:0'))

In [12]:
# Find the maximum and minimum index values of the output of 7.
mini = torch.argmin(c)
maxi = torch.argmax(c)
mini, maxi

(tensor(0, device='cuda:0'), tensor(3, device='cuda:0'))

In [13]:
# Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

torch.manual_seed(7)
d= torch.rand(size=(1,1,1,10))
e= d.squeeze()

print(d,d.shape)
print(e,e.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
