<a href="https://colab.research.google.com/github/Abhinavpanjiyar1/100-days-python-projects/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#This is my Title
This is Regualar text

In [1]:
print("hey i am abhinav panjiyar")

hey i am abhinav panjiyar


In [8]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
print (torch.__version__)

2.3.0+cu121


#Introduction to Tensors

Creating tensors

Pytorch tensor are created using torch.tensor


In [10]:
#scalar

scalar =  torch.tensor(5)
scalar


tensor(5)

In [5]:
scalar.ndim

0

In [11]:
scalar.item()

5

In [13]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [14]:
vector.ndim

1

In [16]:
vector.shape

torch.Size([2])

In [20]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [21]:
MATRIX.ndim

2

In [22]:
MATRIX[1]

tensor([ 9, 10])

In [23]:
MATRIX.shape

torch.Size([2, 2])

TENSOR

In [24]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,6],
                        [1,2,4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 6],
         [1, 2, 4]]])

In [25]:
TENSOR.ndim

3

In [26]:
TENSOR.shape

torch.Size([1, 3, 3])

In [27]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 6],
        [1, 2, 4]])

In [34]:
# create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0385, 0.5937, 0.5539, 0.2378],
        [0.8812, 0.4097, 0.4137, 0.9189],
        [0.3641, 0.9585, 0.5425, 0.1185]])

In [35]:
random_tensor.ndim

2

In [37]:
# create a random tensor with similar shape  to an image tensor

random_image_size_tensor= torch.rand(size=(3,224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

# ZEROES AND ONES

In [46]:
#create a tensor of all zeroes
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [48]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [49]:
ones.dtype

torch.float32

In [54]:
### Create a range of tensors and tensors-like

one_to_ten=torch.arange(start=2, end=10, step=1)
one_to_ten


tensor([2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0])

In [57]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor


tensor([3., 6., 9.])

In [58]:
float_16_tensor = float_32_tensor.type(torch.float32)
float_16_tensor


tensor([3., 6., 9.])

In [60]:
float_64_tensor = float_32_tensor.type(torch.float64)
float_64_tensor


tensor([3., 6., 9.], dtype=torch.float64)

In [61]:
float_16_tensor * float_32_tensor * float_64_tensor

tensor([ 27., 216., 729.], dtype=torch.float64)

In [62]:
some_tensor = torch.rand(3,4)
some_tensor


tensor([[0.2747, 0.9042, 0.2956, 0.1633],
        [0.0703, 0.7027, 0.9946, 0.9995],
        [0.1544, 0.4973, 0.2911, 0.3558]])

In [63]:
print(some_tensor)
print(f"shape of tensor: {some_tensor.shape}")
print(f"datatype of tensor: {some_tensor.dtype}")
print(f"devvice tensor is on: {some_tensor.device}")



tensor([[0.2747, 0.9042, 0.2956, 0.1633],
        [0.0703, 0.7027, 0.9946, 0.9995],
        [0.1544, 0.4973, 0.2911, 0.3558]])
shape of tensor: torch.Size([3, 4])
datatype of tensor: torch.float32
devvice tensor is on: cpu


In [64]:
# ADDITION
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [65]:
# MULTIPLLICATION

tensor * 10

tensor([10, 20, 30])

In [66]:
torch.matmul(tensor, tensor)

tensor(14)

In [72]:

value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)



tensor(14)


In [75]:
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])

tensor_B = torch.tensor([[7,8],[2,5],[6,5]])

torch.mm(tensor_A, tensor_B.T)


tensor([[23, 12, 16],
        [53, 26, 38],
        [83, 40, 60]])

In [76]:
tensor_B.shape

torch.Size([3, 2])

In [77]:
tensor_B.T.shape


torch.Size([2, 3])

In [78]:
torch.mm(tensor_A.T, tensor_B)

tensor([[43, 48],
        [58, 66]])

In [79]:
tensor_A.T.shape

torch.Size([2, 3])

# Finding Min MAX  SUM (TENSOR AGGRESSION)


In [81]:
x =  torch.arange(0,100,10)
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [85]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [83]:
torch.max(x)


tensor(90)

In [84]:
torch.sum(x)

tensor(450)

In [86]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [87]:
x.argmin()

tensor(0)

In [88]:
x.argmax()

tensor(9)

## Reshaping stacking squeezing and unsqueezing


# INDEXING (selecting data from tensors)

In [90]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [91]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [92]:
x[0][0]

tensor([1, 2, 3])

In [96]:
x[0][2][2]

tensor(9)

In [97]:
x[:, 1, 1]

tensor([5])

In [98]:
x[0, 0, :]

tensor([1, 2, 3])

In [100]:
x[:, :, 2]

tensor([[3, 6, 9]])

# PYTORCH TENSOR AND NUMPY

In [104]:
# Numpy array to tensor

import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [105]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [106]:
# tensor to numpy

tensor= torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [107]:
tensor = tensor+1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

REPRODUCbility


In [2]:
import torch
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.6271, 0.0200, 0.8912, 0.8506],
        [0.9498, 0.9959, 0.3756, 0.7012],
        [0.5017, 0.4558, 0.2409, 0.2633]])
tensor([[0.1442, 0.6699, 0.1999, 0.5702],
        [0.9109, 0.7513, 0.5166, 0.6930],
        [0.1619, 0.1245, 0.5346, 0.1845]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
